# Generated by Django 6.0.2 on 2026-03-08 13:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["email"], "verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
