# Generated by Django 6.0.2 on 2026-02-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("heading", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержимое")),
                ("image", models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="Изображение")),
                ("publication", models.BooleanField(default=True, verbose_name="Признак публикации")),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("number_views", models.IntegerField(default=0, verbose_name="Количество просмотров")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "db_table": "article",
                "ordering": ["created_at"],
            },
        ),
    ]
