# Generated by Django 6.0.2 on 2026-02-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-created_at"], "verbose_name": "Статья", "verbose_name_plural": "Статьи"},
        ),
    ]
