# Generated by Django 6.0.2 on 2026-03-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_article_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="user",
            new_name="owner",
        ),
    ]
