# Generated by Django 6.0.2 on 2026-02-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(max_length=250, verbose_name="Адрес")),
                ("country", models.CharField(max_length=50, verbose_name="Страна")),
                ("inn", models.IntegerField(verbose_name="ИНН")),
                ("phone", models.CharField(max_length=12, verbose_name="Контактный телефон")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "db_table": "contacts",
                "ordering": ["phone"],
            },
        ),
    ]
