# Generated by Django 6.0.2 on 2026-03-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication",
            field=models.BooleanField(default=True, verbose_name="Признак публикации"),
        ),
    ]
