# Generated by Django 6.0.2 on 2026-03-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="images/default.jpg", null=True, upload_to="images/", verbose_name="Изображения"
            ),
        ),
    ]
