# Generated by Django 6.0.2 on 2026-03-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="images/default.jpg", upload_to="images/", verbose_name="Изображения"
            ),
        ),
    ]
