# Generated by Django 6.0.2 on 2026-03-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="publication",
            field=models.BooleanField(default=False, verbose_name="Признак публикации"),
        ),
    ]
