# Generated by Django 6.0.2 on 2026-03-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_options_alter_product_publication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user",
            new_name="owner",
        ),
    ]
